# Generated by Django 4.0.3 on 2022-03-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
