# Generated by Django 4.0.3 on 2022-03-07 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_created_at_wishlist_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='status',
            new_name='published',
        ),
    ]
