# Generated by Django 4.0.3 on 2022-03-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_status_wishlist_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
