# Generated by Django 4.0.3 on 2022-03-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
